version: "3.9"
services:
  srsran:
    build:
      context: .
      args:
        UHD_BRANCH: "master"
    container_name: srsran
    network_mode: host
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rmw'
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./configs:/configs
      - ./logs:/logs
      - uhd_images:/usr/local/share/uhd_images
    tty: true
    stdin_open: true
volumes:
   uhd_images:

